### ISSUE TITLE
Move test involving embedded database to an integration test project and mock in unit tests

### ISSUE THREAD

**Issue by krichter722** [OrienteerBAP/Orienteer#146]
Unit tests shouldn't open sockets and start embedded database servers. That's integration testing. Afaik that's done in separate `-it` projects in `maven`. The existing tests which are in fact integration tests should be moved to such a project. Unit tests should use mocks.

There's the `orienteer-archetype-war` project whose meaning I don't fully understand. It executes integration tests which run even if `-DskipTests=true` is specified as `maven` option (might be a separate issue).

**Comment by PhantomYdn** [comment]
Let me partially disagree with you. Tests are directly related to working with OrientDB and they are organized in pretty much the same way as tests in OrientDB themself. If you have concern about opening sockets: that might be disabled in orienteer-test.properties

**Comment by krichter722** [comment]
> Let me partially disagree with you. Tests are directly related to working with OrientDB and they are organized in pretty much the same way as tests in OrientDB themself. If you have concern about opening sockets: that might be disabled in orienteer-test.properties

Noted.

I guess it's just `TestMyWebApplication.java` in `orienteer-archetype-war` which takes for ever and isn't controlled with `-DskipTests=true`. That should be changed, right?

**Comment by PhantomYdn** [comment]
I see what do you mean... orienteer-archetype-war is maven archetype for quick bootstraping of new projects on top of Orienteer.  https://maven.apache.org/guides/introduction/introduction-to-archetypes.html
And for now I set -DskipTests=false for running packaging of this archetype just to be sure that archetype build is correct. If can find a way how to pass "skipTests" from parent maven process to child one: please let me know.

If you don't want to build everything on every small change: I recommend to work just within orienteer-core. And btw, it's possible to run "mvn clean jetty:run" for this jar project.

**Comment by PhantomYdn** [comment]
It's possible to use -DskipITs
