### ISSUE TITLE
Saving a new class fails with error "User 'writer' has no the permission to execute the operation 'Update' against the resource:"

### ISSUE THREAD

**Issue by krichter722** [OrienteerBAP/Orienteer#153]
Saving a new class fails with `User 'writer' has no the permission to execute the operation 'Update' against the resource: ResourceGeneric [name=CLUSTER, legacyName=database.cluster].internal`. See screenshots for details.

![orienteer_demo_not_writable-0](https://cloud.githubusercontent.com/assets/4369372/6866099/fe67b2f8-d474-11e4-9be5-7b9f62440cec.png)

Overview of user `writer`:

![orienteer_demo_not_writable-1](https://cloud.githubusercontent.com/assets/4369372/6866104/10a5d6ca-d475-11e4-9db1-7d54aabcb85c.png)

experienced with 1.0-SNAPSHOT

**Comment by PhantomYdn** [comment]
Did you try repeat? I had sometimes this bug... It's pretty unpredictable and it seems to be in OrientDB.
And did you try with other class name?

**Comment by krichter722** [comment]
Reproducible all the time with arbitrary class names and differing and equal short names on all clusters.

**Comment by PhantomYdn** [comment]
Related issue in OrientDB: https://github.com/orientechnologies/orientdb/issues/3826

**Comment by PhantomYdn** [comment]
Fixed just on [demo site](http://demo.orienteer.org), but should be fixed in OrientDB finally.

**Comment by krichter722** [comment]
Great! Thank you!

**Comment by krichter722** [comment]
I'm now getting this error during saving a new class when I run Orienteer locally on GlassFish 4.1 with cdb7f406e13e1821924c287632317932679c3ea1.

**Comment by PhantomYdn** [comment]
That's not Orienteer issue, but OrientDB, so it will be repeated everytime when you are using new OrientDB database.

To fix this issue:
1. Goto 'writer' role  (Roles->writer)
2. Update "Rules" field: put 7 for 'database.cluster.internal'

**Comment by krichter722** [comment]
Ahh, thank you. Should work by default, though, right?

**Comment by PhantomYdn** [comment]
Yep - that's how it was fixed on [demo site](http://demo.orienteer.org).
