### ISSUE TITLE
Widget for OTriggered modification

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#284]
According to provided [OrientDB documentation](http://orientdb.com/docs/2.1/Dynamic-Hooks.html) if document inherited from OTiggered it's possible to specify listed fields as a reference to a OFunction and that function will be triggered on required event.

So this widget should allow to set a references to OFunction for a set of predefined fields. The main problem why generic interface can't be used: those fields are not registered as properties of OTriggered - so they need to be added ondemand to a document

**Comment by PhantomYdn** [comment]
Please take a look into related issue #324.

**Comment by ankitbansal** [comment]
From the documentation, it looks like trigger is only applicable for subclasses of OTriggered and documents of a subclass rather than an OTriggered class itself.

**Comment by PhantomYdn** [comment]
That's right, but if you will define selector="OTriggered": widget will show up on all childrens of OTriggered

**Comment by ankitbansal** [comment]
By this we will have a trigger for individual documents. Do we have another functionality to attach trigger to a list of document matching a criteria (similar to account example in document).

**Comment by PhantomYdn** [comment]
See another issue on you: #324 . So there are 2 different places where it's possible to define triggers: class level and document level.

**Comment by ankitbansal** [comment]
Actually what I meant was user might be more interested in having a trigger on a list of document matching a criteria rather than going for individual documents and adding trigger for each. Class level trigger is good but that is applicable for all documents of a class not to a subset of documents of a class.

**Comment by ankitbansal** [comment]
Got it.

**Comment by ankitbansal** [comment]
Function names are coming in upper case. I am using OrientDbWebSession.get().getDatabase().getMetadata().getFunctionLibrary().getFunctionNames(). Can you please suggest what needs to be used.

**Comment by PhantomYdn** [comment]
I recommend just to use listing of OFunction documents.
Regarding Save: please let me know what's extra logic required for save?
