### ISSUE TITLE
Pivottable sometimes failing on "special" data provided by OrientDB

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#379]
Depends on: https://github.com/nicolaskruchten/pivottable/issues/452

**Comment by nicolaskruchten** [comment]
I have a PR open which will likely address this if merged, and I'd love some feedback on it! nicolaskruchten/pivottable#600

**Comment by PhantomYdn** [comment]
@nicolaskruchten , thank you! Finally it works. Closing this our issue.

**Comment by nicolaskruchten** [comment]
Great! keep an eye out for a couple more nice features on PivotTable.js in the next few days, like drill-through support, and much-improved filter menus :)
