### ISSUE TITLE
Move to OrientDB 2.2

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#397]

**Comment by DKorchuganov** [comment]
Hi, guys!

Which version of OrientDB is compatible with Orienteer 1.1? I didn't find any OrientDB version requirements in docs...
And what is an estimated date of versions 1.2 and 1.3?

Best regards,
Denis

**Comment by PhantomYdn** [comment]
Hi! First of all, it's not recommended to use Orienteer version 1.1: it's pretty old - a lot of cool features are absent. Please use Orienteer 1.2 SNAPSHOT version or https://hub.docker.com/r/orienteer/orienteer/ with tag "latest". We are going to close Version 1.2 as soon as BPM will be mature enough: preliminary in ~1 month. If you definitily need to have static version instead of snapshot: please let me know - we can speed up closing version 1.2 for you.
Orienteer 1.2 is using OrientDB 2.1.19

**Comment by PhantomYdn** [comment]
Done long time ago. Currently supported version is 2.2.25. Closing.
