### ISSUE TITLE
Tab ordering in a document

### ISSUE THREAD

**Issue by afoxinatree** [OrienteerBAP/Orienteer#403]
Repro
1 By default, a property is displayed on the tab Parameters. I cannot specify the order of this tab relative to others.
2 If I specity for a property that it should be destpayed on a tab Parameters, the document will show two tabs with similar name "Parameters".

Suggestion
If we make the default value Tab:Parameters and make it obligatory, both issues from Repro wll be fixed.
![image](https://cloud.githubusercontent.com/assets/17749672/16178285/4c92007a-364c-11e6-9bf3-e50a293a671e.png)

**Comment by PhantomYdn** [comment]
Currently issue is fixed. Order can be specified by corresponding properties added to a tab.
