### ISSUE TITLE
UI Readonly doesn't work for 'table' visualization

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#450]
1. Create ClassAlice
2. Create ClassBob
3. Create ClassAlice.linklistToBob LINKLIST with 'table' visualization, reverse, UI READONLY
4. Create ClassBob.linkToAlice LINK with 'listbox' visualization, reverse
5. Create some documents of ClassAlice
6. Create document of ClassBob, set reference to any ClassAlice
7. Go to linked ClassAlice fullview

ER: ClassBob is showed in table widget, control menu buttons not available
AR: Control menu is available, it is possible to edit ClassBob documents from ClassAlice

**Comment by PhantomYdn** [comment]
Only Edit and Save can be shown if structure can't be changed.

**Comment by PhantomYdn** [comment]
Fixed in mentioned above commit
