### ISSUE TITLE
Pivot table widget should refresh without page reload

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#458]
1. Add pivot widget to ListAll widget
2. Configure pivot chart
3. Select some records
4. Press [Delete] to delete documents

ER: Pivot table refreshes, values updated
AR: To refresh pivot table it's need to reload web-page (f5)

**Comment by PhantomYdn** [comment]
Ivan,

You will need to use existing Behavior for catching model change notifications: if event happened you should regenerate random salt and refresh pivot.

**Comment by PhantomYdn** [comment]
Was fixed here: https://github.com/OrienteerBAP/Orienteer/pull/469
