### ISSUE TITLE
fix DATE type field wrong behavior

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#466]
1. Create a Class with DATE property
2. Create a document of the class
3. Fill DATE type property
4. Save document
5. Refresh webpage

ER: entered DATE value is saved
AR: DATE value is decreased by day

**Comment by PhantomYdn** [comment]
Fixed here: https://github.com/OrienteerBAP/Orienteer/commit/feff78c23bda6bed0ec6a13759bafd2d6d162dd9
