### ISSUE TITLE
Default values should be visible in GUI when object created

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#467]
1. Create ClassA with **name** and **linkToEnum** (type = LINK, visualization = listbox) attributes
2. Create Enum class with **name** attribute
3. Create some instances of Enum class: Obj1 and Obj2
4. Go to Obj1 and check link to object in browser bar, for example **42:1**
5. Go to ClassA and set default value to **linkToEnum** as ``#42:1``
6. Create and instance of ClassA

ER: In UI there is selected value in **linkToEnum** listbox to **Obj1**
AR: default value is visible only after saving object and refreshing the page

**Comment by PhantomYdn** [comment]
It's possible in OrientDB 2.2. So awaiting jump to 2.2

**Comment by PhantomYdn** [comment]
Done by moving to OrientDB 2.2: issue #397
