### ISSUE TITLE
Logout user after period of inactivity

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#476]
1. Login to system
2. Do nothing for 2 hours

ER: User will be logged out of session to login screen
AR: System sleeps at the last screen, after any action user is redirected to login screen

**Comment by PhantomYdn** [comment]
Seems this was changed drastically in latest Apache Wicket 7.8.0. Currently Orieent doesn't redirect in background to login page, but page behave quite logically in case of session expire. Closing by now.
