### ISSUE TITLE
Error While Connecting to localhost/GratefulDeadConcerts

### ISSUE THREAD

**Issue by py563** [OrienteerBAP/Orienteer#477]
Last cause: Class 'OPERSPECTIVE' was not found in database 'GratefulDeadConcerts'
	DB name="GratefulDeadConcerts"
Full Error in below pdf file
[Unexpected RuntimeException.pdf](https://github.com/OrienteerBAP/Orienteer/files/851445/Unexpected.RuntimeException.pdf)

changed .properties file as mentioned in readme, tried with version 2.2.15/2.2.17

**Comment by PhantomYdn** [comment]
Hello, it's really strange exception. All required modules are being installed during application startup - so after first load of Orienteer on GratefulDeadConcerts DB - all classes should be installed.

Can you please provide more detailed step by step to reproduce? And is there any other exceptions in logs during startup of the app?

**Comment by py563** [comment]
i tried with latest version of orientdb, whereas you were using 2.1.19. OrienteerGraph project is working well with other database in 2.1.19. I will try again on Gratefuldead on 2.1.19 and reply.

**Comment by PhantomYdn** [comment]
That's known maven problem under windows. Please check your mvn bin directory: both mvn.cmd and mvn.bat should exist.  If some is missing: just copy other file and name it correspondingly.

**Comment by PhantomYdn** [comment]
Outdated and no reply. Closing

**Comment by py563** [comment]
Sorry llia, it did work.
