### ISSUE TITLE
Hide Perspectives from unauthorized users

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#482]
Perspectives that not selected in Perspective attribute for OUser or ORole should not be available in dropdown Perspective menu

**Comment by PhantomYdn** [comment]
@WeaxMe , could you please describe here how that can be done through ORestricted and close the ticket?

**Comment by WeaxMe** [comment]
@tim-lucida for adjust user access for Perspective need configure fields in `ORestricted` subclass.

1. Set class `ORestricted` as parent for class `OPerspective`
2. Open perspective document and choose tab `Security`
3. For allow user to read this perspective choose user document or role document in field `_allowRead`

### True way
1. Create role `myRole` 
2. Create perspective `myPerspective`
3. Add link to `myRole` in field `_allowRead` in document `myPerspective`

Btw. you can use [orienteer-users](https://github.com/OrienteerBAP/Orienteer/tree/master/orienteer-users) for configure user oriented system.
