### ISSUE TITLE
How to cluster deploy?

### ISSUE THREAD

**Issue by hanyou** [OrienteerBAP/Orienteer#487]
i will deploy several instance, how to cluster and load balance?

**Comment by PhantomYdn** [comment]
@hanyou , all our components are supporting clusterization: Apache Wicket and OrientDB. But we haven't tested fully this deployment type. If your needs under 500 concurrent users: average hardware wtih singly Orienteer can handel that. But if you are especially interested in clustering - lets colloborate closely on this topic.
