### ISSUE TITLE
Make custom widget for DATE attribute type

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#488]
For date attribute type it would be more user-friendly to use calendar widget with month and years only.
On the first level of the widget are months, on the second are years, on the third are decades
See example below
[http://4.bp.blogspot.com/-QAT3RL3VoMo/TxrQ_nUnh2I/AAAAAAAAAAs/HeiI5YzqRj8/s1600/CalendarYearView.png](url)

**Comment by PhantomYdn** [comment]
@tim-lucida , why issue was closed? Do you think it's not valid?
