### ISSUE TITLE
Allow to minimise left menu panel

### ISSUE THREAD

**Issue by tim-lucida** [OrienteerBAP/Orienteer#499]
1. Move search bar to the header
2. Add hide icon to the menu
3. Click on the [hide] button should minimise menu to the icons
(if menu has two or three levels then show only high-level icon)
4. Click on the maximize button should show the full menu with menu item selected

The wireframes
https://i.gyazo.com/4d1a4a7338525f3823efa5a8ef04f265.png
https://i.gyazo.com/841e093a5cc9408803dcd2cb92136296.png

this enhancement is to increase space for tables or reports with many columns

**Comment by PhantomYdn** [comment]
Implemented by moving to Core UI. There is an icon to minimize the left menu.
