### ISSUE TITLE
Resolve problem with download Orienteer modules when modules jar file is in maven repository

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#531]
1. Download all Orienteer modules
2. Restart Orienteer
3. Delete all Orienteer modules
4. Restart Orienteer
5. Download all Orienteer modules - **FAILED**.
We can't download all Orienteer modules.

**Comment by PhantomYdn** [comment]
Any details? Exception?

**Comment by WeaxMe** [comment]
ArtifactResolutionException. I have been deleted Orienteer module's artifact from maven repository and then run test when Orienteer modules downloads and delete 100 times and all was good.

**Comment by PhantomYdn** [comment]
Fixed previously. Somewhere around this commit: https://github.com/OrienteerBAP/Orienteer/commit/a89251f27c95446b45a37a8c88fd8aabe108f709
