### ISSUE TITLE
Bug with width of Orienteer tables

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#543]
Fix bug with width of Orienteer tables in different locales.
**Choose Orienteer locale to ru and width of Orienteer tables will be very big**

**Comment by PhantomYdn** [comment]
Can't reproduce. Could you please attach some screenshot?

**Comment by WeaxMe** [comment]
![2017-08-11 10-25-55](https://user-images.githubusercontent.com/20383875/29204525-348cfa48-7e80-11e7-9b09-0d04310fbd96.png)
![2017-08-11 10-31-59](https://user-images.githubusercontent.com/20383875/29204558-76b60eb4-7e80-11e7-88c0-6d183b5c6d31.png)

Laptop screen: 1366x768

**Comment by WeaxMe** [comment]
There is new design in v1.4 and this bug already fixed. 
So this issue already done.
