### ISSUE TITLE
Errors when use two slash in URL

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#567]
When use two slash in URL I give too many errors in respond from server.
**Steps for reproduce:**
In URL write {orienteer.doman}// (use two slash at the end). Example: localhost:8080//
**Result:**
![2017-08-19 13-56-00](https://user-images.githubusercontent.com/20383875/29486067-3bb8b2b4-84e6-11e7-8dd7-10d373f667fc.png)
![2017-08-19 13-57-26](https://user-images.githubusercontent.com/20383875/29486074-61581762-84e6-11e7-89b3-21cd66e3e5c6.png)

**Comment by PhantomYdn** [comment]
Looks like Wicket issue. Email was send - lets see what community will reply.
Moving to 1.4 by now.

**Comment by PhantomYdn** [comment]
It depends on the following Wicket issue: https://issues.apache.org/jira/browse/WICKET-6473

**Comment by PhantomYdn** [comment]
Issue was fixed in Wicket and automatically fixed in Orienteer
