### ISSUE TITLE
Bug with "access denied" feedback message

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#569]
When user don't have permission for some action "access denied" message creates on page but then page reloads and I can't see this message.
I test it in 'orienteer-architect' when create class by user that don't have permission for create class (user don't have permission UPDATE in database.cluster.internal)

**Comment by PhantomYdn** [comment]
Can you please specify how to reproduce the issue?

**Comment by PhantomYdn** [comment]
Is the issue still exist?

**Comment by WeaxMe** [comment]
This issue is not relevant
