### ISSUE TITLE
Create docs for 'orienteer-architect'

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#575]
1) Create user guide for 'orienteer-architect'
2) Create description of code executing 'orienteer-archtiect'

**Comment by WeaxMe** [comment]
Add in [docs page](https://github.com/OrienteerBAP/Orienteer/wiki/Orienteer-Architect-User-Guide)

**Comment by PhantomYdn** [comment]
Reference to wiki added here: https://github.com/OrienteerBAP/Orienteer/commit/5dd29157c4c695d29865c490561ca2c5c7cbcd1c
