### ISSUE TITLE
Filtering doesn't work for LINKLIST/LINKSET generated tables

### ISSUE THREAD

**Issue by PhantomYdn** [OrienteerBAP/Orienteer#584]
Lets imagine the following model:

```
class Folder
property name
property files (LINKLIST to documents of class File) visualization is 'table'

class File
property name
property folder (LINK to document of class Folder)
```

If you open page `/browse/File`: there are sorting and filtering. But if you go to some Folder and see table of files: there are no filtering. Please add.

**Comment by WeaxMe** [comment]
Fixed in #589
