### ISSUE TITLE
Non authorize access on read 

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#609]
We can read document data and not be authorize.

Steps for reproduce
---
1. Go to some document and copy url like `/doc/1259:0/`. We need only RecordID (ORID). Log out from Orienteer
2. Paste url from step 1 in string `http://localhost:8080/` it's must be something like `http://localhost:8080/doc/1259:0/`. We go to document page and see all data from document without authorize.

Anyone can see information about users or their sessions!
--

**Comment by PhantomYdn** [comment]
By default all guests of Orienteer have rights of user "reader". This user by default have rights to read from all classes.  To secure your Orienteer installation you can:
1) Either adjust security rights for "reader" user
2) Or change orienteer.properties to use other user as default for Orienteer guests

**Comment by WeaxMe** [comment]
Thank, you!
