### ISSUE TITLE
Redirect user to page which user see after login

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#637]
As default not logged users have "read" privileges, so they can read some page, but when user clicks `Login` he redirects to login page. That's OK. But when user logged he redirects to `Schema Page`  not  to page which user see.
May be it will be better to redirect user on page which user read, after login?

**Comment by PhantomYdn** [comment]
If user go to a page where he doesn't have rights - it will be requested for username/password and then navigated to original page he requested. So Orienteer catch originally requested page and send user finally to it.
But if there is no originally requested page: user will be navigated to home page.
So everything working as designed and described above by me. Where is the problem?
