### ISSUE TITLE
Create annotation like @Value in Lombok for ODocumentWrapper

### ISSUE THREAD

**Issue by WeaxMe** [OrienteerBAP/Orienteer#693]
Annotation `@Value` or `@Data` in Lombok project speed up development, but we can't use it with document wrapper, because need update document, so it will be cool for create something like this annotations for document wrappers

**Comment by WeaxMe** [comment]
Need create this features, because there is a lot of time need for write simple things. That time can be used for write something funny

**Comment by PhantomYdn** [comment]
With #777 this seems to be not actual. Please close if you agree.
